### DISCUSSION TITLE
Docker Compose File ( --basic-auth unfunctional ) [ SOLVED ]

### DISCUSSION THREAD

**Discussion by NorkzYT** [abhinavsingh/proxy.py#1254] [Q&A] [answered]
I made a `docker-compose.yml` file based on the docker container parameters and the image, when I added the authentication parameter the logs would say that the authentication plugin is on, although when I use Curl in CLI or the app, FOGLDN Proxy Tester,  the connection fails.

My `docker-compose.yml` file:
```
version: '3.8'
services:

  proxy.py:
    image: abhinavsingh/proxy.py:v2.4.4rc3.dev7
    hostname: proxy.py
    container_name: proxy.py
    restart: unless-stopped
    ports:
      - 899:8899
    networks:
      - proxy
    command: --basic-auth user:password
networks:
  proxy:
    driver: bridge
    external: true
```

Output logs:
```
2022-08-11 16:27:27,199 - pid:1 [I] plugins.load:85 - Loaded plugin proxy.http.proxy.HttpProxyPlugin
2022-08-11 16:27:27,200 - pid:1 [I] plugins.load:85 - Loaded plugin proxy.http.proxy.auth.AuthPlugin
2022-08-11 16:27:27,200 - pid:1 [I] tcp.listen:80 - Listening on 127.0.0.1:8899
2022-08-11 16:27:27,210 - pid:1 [I] pool.setup:105 - Started 4 acceptors in threadless (local) mode
```

Any help would be greatly appreciated!

**Comment by abhinavsingh** [comment, marked as answer]
@NorkzYT Hi, I am not a heavy docker compose user, but I gave it a try using docker container.  Seems to work as expected.

- Note that in your config, your port mapping is `899:8899`, probably you want `8899:8899`
- Further, also pass `--hostname 0.0.0.0` flag to docker container in case your clients are unable to reach proxy within container

<img width="1317" alt="Screenshot 2022-08-13 at 12 06 19 PM" src="https://user-images.githubusercontent.com/126065/184472015-c288ec68-758b-4479-bafd-887a93196588.png">

Let me know if you still run into any issue

**Reply by NorkzYT** [reply]
Understood mate, I will do that tomorrow and will advise on any changes, thanks for your help!

**Reply by NorkzYT** [reply]
> 

I added `--hostname 0.0.0.0` and now it's fully working, thank you very much mate! I read about adding the flag in your documentation, although I thought to add it but then I just forgot entirely after an hour, haha.

For anyone who wants the revised `docker-compose.yml` file:

```
version: '3.8'
services:

  proxy.py:
    image: abhinavsingh/proxy.py:v2.4.4rc3.dev7
    hostname: proxy.py
    container_name: proxy.py
    restart: unless-stopped
    ports:
      - 9899:8899
    networks:
      - proxymoxy
    command: --basic-auth user:pass --hostname 0.0.0.0
networks:
  proxymoxy:
    driver: bridge
    external: true
```


If someone doesn't wants the authentication values to appear in the `docker-compose.yml` file then replace `user:pass` to `${AUTH}` and make a `.env` file in the same folder the `docker-compose.yml` file is at and the contents inside should be the following:

```
AUTH=user:pass
```
